INSERT INTO ENFERMEDADES (nombre) VALUES
('Gripe'),
('Resfriado común'),
('COVID-19'),
('Neumonía'),
('Tuberculosis'),
('Hepatitis A'),
('Hepatitis B'),
('Hepatitis C'),
('VIH/SIDA'),
('Malaria'),
('Dengue'),
('Zika'),
('Chikungunya'),
('Ébola'),
('Varicela'),
('Sarampión'),
('Rubéola'),
('Paperas'),
('Tos ferina'),
('Meningitis bacteriana'),
('Meningitis viral'),
('Infección urinaria'),
('Otitis media'),
('Faringitis estreptocócica'),
('Amigdalitis'),
('Gastroenteritis viral'),
('Gastroenteritis bacteriana'),
('Hipertensión arterial'),
('Diabetes tipo 1'),
('Diabetes tipo 2'),
('Obesidad'),
('Colesterol alto'),
('Artritis reumatoide'),
('Artrosis'),
('Asma'),
('EPOC'),
('Fibrosis pulmonar'),
('Insuficiencia renal crónica'),
('Insuficiencia cardíaca'),
('Enfermedad coronaria'),
('Arritmias'),
('Cáncer de pulmón'),
('Cáncer de mama'),
('Cáncer de colon'),
('Cáncer de próstata'),
('Cáncer de hígado'),
('Cáncer de páncreas'),
('Cáncer de piel (melanoma)'),
('Leucemia'),
('Linfoma de Hodgkin'),
('Linfoma no Hodgkin'),
('Cáncer de tiroides'),
('Migraña'),
('Epilepsia'),
('Esclerosis múltiple'),
('Alzheimer'),
('Parkinson'),
('Trastorno bipolar'),
('Esquizofrenia'),
('Depresión'),
('Ansiedad generalizada'),
('Trastorno obsesivo-compulsivo'),
('Autismo'),
('TDAH'),
('Úlcera gástrica'),
('Colitis ulcerosa'),
('Enfermedad de Crohn'),
('Síndrome de intestino irritable'),
('Hígado graso'),
('Cálculos biliares'),
('Pancreatitis'),
('Reflujo gastroesofágico'),
('Psoriasis'),
('Eczema'),
('Acné'),
('Vitiligo'),
('Alopecia areata'),
('Melanoma'),
('Dermatitis atópica'),
('Urticaria crónica'),
('Anemia ferropénica'),
('Hemofilia'),
('Trombosis venosa profunda'),
('Embolia pulmonar'),
('Lupus eritematoso sistémico'),
('Esclerodermia'),
('Gota'),
('Osteoporosis');